/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import autocancel.app.elasticsearch.AutoCancel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Object t = new Object() {
            @Override
            public String toString() {
                return "Task 1";
            }
        };
        AutoCancel.onTaskCreate(t);
        Runnable r = new Runnable() {
            @Override
            public void run() {
                for (Integer i = 0; i < 10; ++i) {
                    System.out.println(i);
                }
            }
        };
        AutoCancel.onTaskQueueInThread(r);
        Thread thread1 = new Thread() {
            @Override
            public void run() {
                AutoCancel.onTaskStartInThread(r);
                try {
                    Thread.sleep(1);
                }
                catch (Exception e) {

                }
                AutoCancel.onTaskFinishInThread();
            }
        };
        thread1.start();
        
        
        try {
            thread1.join();
        }
        catch (Exception e) {

        }
        AutoCancel.onTaskFinishInThread();
        AutoCancel.onTaskExit(t);
        System.out.println("Finish 0");

        Object t1 = new Object() {
            @Override
            public String toString() {
                return "Task 2";
            }
        };
        AutoCancel.onTaskCreate(t1);
        Runnable r1 = new Runnable() {
            @Override
            public void run() {
                for (Integer i = 0; i < 11; ++i) {
                    System.out.println(i);
                }
            }
        };
        AutoCancel.onTaskQueueInThread(r1);
        AutoCancel.onTaskStartInThread(r1);
        AutoCancel.onTaskFinishInThread();
        AutoCancel.onTaskExit(t1);
        System.out.println("Finish 1");
    }
}
