/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.lang.management.ManagementFactory;
import java.lang.management.ThreadMXBean;
import java.util.List;

import autocancel.app.elasticsearch.AutoCancel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AutoCancel.start();

        System.out.println(new App().getGreeting());
        Object t = new Object() {
            @Override
            public String toString() {
                return "Task 1";
            }
        };
        AutoCancel.onTaskCreate(t);
        Runnable r = new Runnable() {
            @Override
            public void run() {
                for (Integer i = 0; i < 10; ++i) {
                    System.out.println(i);
                }
            }
        };
        AutoCancel.onTaskQueueInThread(r);
        Thread thread1 = new Thread() {
            @Override
            public void run() {
                AutoCancel.onTaskStartInThread(r);
                try {
                    Thread.sleep(100);
                }
                catch (Exception e) {

                }
                AutoCancel.onTaskFinishInThread();
            }
        };
        thread1.start();
        
        try {
            thread1.join();
        }
        catch (Exception e) {

        }
        AutoCancel.onTaskFinishInThread();
        AutoCancel.onTaskExit(t);
        System.out.println("Finish 0");

        Object t1 = new Object() {
            @Override
            public String toString() {
                return "Task 2";
            }
        };
        AutoCancel.onTaskCreate(t1);
        Runnable r1 = new Runnable() {
            @Override
            public void run() {
                for (Integer i = 0; i < 11; ++i) {
                    System.out.println(i);
                }
            }
        };
        AutoCancel.onTaskQueueInThread(r1);
        AutoCancel.onTaskStartInThread(r1);
        AutoCancel.onTaskFinishInThread();
        AutoCancel.onTaskExit(t1);
        try {
            Thread.sleep(1000);
        }
        catch (Exception e) {

        }
        AutoCancel.stop();
        System.out.println("Finish 1");

        ThreadMXBean threadMXBean = ManagementFactory.getThreadMXBean();

        Long currentThreadStart = threadMXBean.getCurrentThreadCpuTime();
        Long start = System.nanoTime();
        Long sum = 0L;
        for (Integer i = 0; i < 1000000; ++i) {
            sum += i;
        }
        Long currentThreadTotal = threadMXBean.getCurrentThreadCpuTime() - currentThreadStart;
        Long total = System.nanoTime() - start;
        System.out.println(String.format("Current thread: %d, Total: %d", currentThreadTotal, total));
    }
}
