/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package autocancel;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class LibraryTest {
	@Test
	void someLibraryMethodReturnsTrue() {}
}
