/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package autocancel;

import autocancel.app.elasticsearch.AutoCancel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        AutoCancel autoCancel = new AutoCancel();
        System.out.println(new App().getGreeting());
    }
}
